# Generated by Django 5.2.4 on 2025-08-05 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(db_index=True, max_length=2, unique=True)),
                ("code_3", models.CharField(max_length=3, unique=True)),
                ("continent", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=3)),
                ("language", models.CharField(max_length=10)),
                ("timezone", models.CharField(max_length=50)),
                ("calling_code", models.CharField(max_length=10)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("esim_supported", models.BooleanField(default=False)),
                (
                    "coverage_quality",
                    models.CharField(
                        choices=[
                            ("excellent", "Excelente"),
                            ("good", "Buena"),
                            ("fair", "Regular"),
                            ("poor", "Limitada"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("flag_emoji", models.CharField(max_length=10)),
                ("is_popular", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GeofenceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("roaming", "Roaming Detectado"),
                            ("plan_suggestion", "Sugerencia de Plan"),
                            ("data_warning", "Advertencia de Datos"),
                            ("welcome", "Bienvenida al País"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "action_button",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("action_url", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geolocation.country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPGeolocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, unique=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("isp", models.CharField(blank=True, max_length=100, null=True)),
                ("org", models.CharField(blank=True, max_length=100, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=50)),
                ("accuracy_radius", models.IntegerField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geolocation.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "detection_method",
                    models.CharField(
                        choices=[
                            ("gps", "GPS"),
                            ("ip", "IP Address"),
                            ("manual", "Manual"),
                            ("cell_tower", "Cell Tower"),
                        ],
                        max_length=20,
                    ),
                ),
                ("accuracy", models.IntegerField(blank=True, null=True)),
                ("is_roaming", models.BooleanField(default=False)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geolocation.country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="NetworkOperator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "network_type",
                    models.CharField(
                        choices=[("4G", "4G LTE"), ("5G", "5G"), ("3G", "3G")],
                        max_length=10,
                    ),
                ),
                ("frequency_bands", models.JSONField(default=list)),
                (
                    "coverage_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operators",
                        to="geolocation.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TravelPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_regions", models.JSONField(default=list)),
                ("average_trip_duration", models.IntegerField(default=7)),
                (
                    "typical_data_usage",
                    models.CharField(
                        choices=[
                            ("light", "Ligero (< 1GB)"),
                            ("moderate", "Moderado (1-5GB)"),
                            ("heavy", "Intenso (> 5GB)"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("prefers_unlimited", models.BooleanField(default=False)),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("budget", "Económico ($5-15)"),
                            ("standard", "Estándar ($15-30)"),
                            ("premium", "Premium ($30+)"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "frequent_countries",
                    models.ManyToManyField(blank=True, to="geolocation.country"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
