[variables]
    NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
    nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
    cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
    cmds = ["python manage.py collectstatic --noinput"]

[start]
    cmd = "gunicorn esim_backend.wsgi:application --bind 0.0.0.0:$PORT"