[phases.setup]
nixPkgs = ['python310', 'postgresql']

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[phases.build]
cmds = ['cd backend && python manage.py collectstatic --noinput']

[start]
cmd = 'cd backend && python manage.py migrate && gunicorn esim_backend.wsgi:application --bind 0.0.0.0:$PORT'
