@echo off
echo 🚀 Iniciando Hablaris Frontend Server...
cd /d "c:\Users\nayel\Esim\frontend"
echo 📁 Directorio: %CD%
echo 📦 Instalando dependencias...
npm install
echo 🏃 Iniciando servidor de desarrollo...
npm run dev
