# Generated by Django 5.2.4 on 2025-08-17 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del país', max_length=100)),
                ('code', models.CharField(help_text='Código ISO del país (US, ES, etc)', max_length=2, unique=True)),
                ('flag_emoji', models.CharField(help_text='Emoji de la bandera', max_length=10)),
                ('is_popular', models.BooleanField(default=False, help_text='Destino popular')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del plan', max_length=200)),
                ('plan_type', models.CharField(choices=[('country', 'País Individual'), ('region', 'Regional'), ('global', 'Global')], default='country', max_length=20)),
                ('data_amount_gb', models.DecimalField(decimal_places=2, help_text='GB de datos', max_digits=8)),
                ('duration_days', models.IntegerField(help_text='Duración en días')),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Precio en USD', max_digits=8)),
                ('is_unlimited', models.BooleanField(default=False, help_text='Datos ilimitados')),
                ('is_featured', models.BooleanField(default=False, help_text='Plan destacado')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, help_text='Para planes de país', null=True, on_delete=django.db.models.deletion.CASCADE, to='esim_backend.country')),
            ],
            options={
                'verbose_name': 'Plan de Datos',
                'verbose_name_plural': 'Planes de Datos',
                'ordering': ['country__name', 'price_usd'],
            },
        ),
        migrations.CreateModel(
            name='ESim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(help_text='ICCID de la eSIM', max_length=22, unique=True)),
                ('qr_code', models.TextField(blank=True, help_text='Datos del código QR')),
                ('status', models.CharField(choices=[('created', 'Creada'), ('activated', 'Activada'), ('suspended', 'Suspendida'), ('expired', 'Expirada')], default='created', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('data_used_mb', models.BigIntegerField(default=0, help_text='MB consumidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(help_text='Plan contratado', on_delete=django.db.models.deletion.CASCADE, to='esim_backend.dataplan')),
                ('user', models.ForeignKey(help_text='Usuario propietario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eSIM',
                'verbose_name_plural': 'eSIMs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la región (Europa, Asia, etc)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('countries', models.ManyToManyField(help_text='Países incluidos en esta región', to='esim_backend.country')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dataplan',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Para planes regionales', null=True, on_delete=django.db.models.deletion.CASCADE, to='esim_backend.region'),
        ),
    ]
