# Generated by Django 5.2.4 on 2025-08-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esim',
            name='status',
            field=models.CharField(choices=[('created', 'Creada'), ('activated', 'Activada'), ('suspended', 'Suspendida'), ('expired', 'Expirada')], default='created', max_length=20),
        ),
    ]
