# Generated by Django 5.2.4 on 2025-08-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esim_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataplan',
            name='country',
        ),
        migrations.RemoveField(
            model_name='region',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='dataplan',
            name='region',
        ),
        migrations.RemoveField(
            model_name='esim',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='esim',
            name='user',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='DataPlan',
        ),
        migrations.DeleteModel(
            name='ESim',
        ),
    ]
