# Generated by Django 5.2.4 on 2025-08-04 02:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "iso_code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="ISO code"
                    ),
                ),
                (
                    "flag_emoji",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="flag emoji"
                    ),
                ),
                ("currency", models.CharField(max_length=10, verbose_name="currency")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "data_amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(100)],
                        verbose_name="data amount (MB)",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("data_only", "Solo Datos"),
                            ("data_sms", "Datos + SMS"),
                            ("data_voice_sms", "Datos + Voz + SMS"),
                            ("unlimited", "Ilimitado"),
                        ],
                        default="data_only",
                        max_length=20,
                        verbose_name="plan type",
                    ),
                ),
                (
                    "validity_days",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 día"),
                            (3, "3 días"),
                            (7, "7 días"),
                            (15, "15 días"),
                            (30, "30 días"),
                            (60, "60 días"),
                            (90, "90 días"),
                        ],
                        verbose_name="validity days",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="discount price",
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="is popular"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "max_speed",
                    models.CharField(
                        default="4G/LTE", max_length=20, verbose_name="max speed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "countries",
                    models.ManyToManyField(
                        to="plans.country", verbose_name="countries"
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Plan",
                "verbose_name_plural": "Data Plans",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(max_length=100, verbose_name="feature name"),
                ),
                (
                    "feature_description",
                    models.TextField(blank=True, verbose_name="feature description"),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(default=False, verbose_name="is highlighted"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="plans.dataplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Feature",
                "verbose_name_plural": "Plan Features",
            },
        ),
    ]
