# Generated by Django 5.2.4 on 2025-08-12 21:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iccid', models.CharField(max_length=22, unique=True, verbose_name='ICCID')),
                ('smdp_address', models.CharField(max_length=255, verbose_name='SM-DP+ Address')),
                ('activation_code', models.TextField(verbose_name='activation code')),
                ('status', models.CharField(choices=[('created', 'Creada'), ('activated', 'Activada'), ('active', 'Activa'), ('suspended', 'Suspendida'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='created', max_length=20, verbose_name='status')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='nickname')),
                ('data_used', models.PositiveIntegerField(default=0, verbose_name='data used (MB)')),
                ('last_usage_update', models.DateTimeField(blank=True, null=True, verbose_name='last usage update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='activated at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('provider_esim_id', models.CharField(blank=True, max_length=100, verbose_name='provider eSIM ID')),
                ('provider_order_id', models.CharField(blank=True, max_length=100, verbose_name='provider order ID')),
            ],
            options={
                'verbose_name': 'eSIM',
                'verbose_name_plural': 'eSIMs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ESimActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.JSONField(blank=True, null=True, verbose_name='device info')),
                ('activation_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='activation IP')),
                ('activation_location', models.CharField(blank=True, max_length=200, verbose_name='activation location')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'eSIM Activation',
                'verbose_name_plural': 'eSIM Activations',
            },
        ),
        migrations.CreateModel(
            name='ESimUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('data_used', models.PositiveIntegerField(verbose_name='data used (MB)')),
                ('total_data_used', models.PositiveIntegerField(verbose_name='total data used (MB)')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('network_operator', models.CharField(blank=True, max_length=100, verbose_name='network operator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'eSIM Usage Log',
                'verbose_name_plural': 'eSIM Usage Logs',
                'ordering': ['-date'],
            },
        ),
    ]
