# Generated by Django 5.2.4 on 2025-08-12 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esims', '0001_initial'),
        ('payments', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='esim',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esim', to='payments.order'),
        ),
        migrations.AddField(
            model_name='esim',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.dataplan'),
        ),
        migrations.AddField(
            model_name='esim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='esimactivation',
            name='esim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to='esims.esim'),
        ),
        migrations.AddField(
            model_name='esimusagelog',
            name='esim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='esims.esim'),
        ),
        migrations.AlterUniqueTogether(
            name='esimusagelog',
            unique_together={('esim', 'date')},
        ),
    ]
